### ISSUE TITLE
Zero (0) is not supported/handled by DTMF 

### ISSUE THREAD

**Issue by robbailey3** [jambonz/sbc-outbound#58]
The regex to get the DTMF body from the request does not handle zero. 

Sending a DTMF request:

```
CSeq: 1 INFO
Call-ID: 5ae225a2-1117-123c-21be-0a20d9f2af94
Max-Forwards: 70
Supported: outbound
User-Agent: SIP.js/0.20.1
Content-Type: application/dtmf-relay
Content-Length: 21

Signal=0
Duration=50
```

Results in an error:

```
{
    "level": 30,
    "time": "2023-01-17T14:37:53.569Z",
    "pid": 2347167,
    "hostname": "ip-172-31-45-152",
    "callId": "5adfb3c7-1117-123c-1c81-0a20d9f2af94",
    "err": {
        "type": "Error",
        "message": "_onInfo: no dtmf in body for application/dtmf-relay",
        "stack": "Error: _onInfo: no dtmf in body for application/dtmf-relay\n    at CallSession._onInfo (/home/admin/apps/sbc-outbound/lib/call-session.js:726:17)\n    at Dialog.emit (node:events:513:28)\n    at Dialog.emit (node:domain:489:12)\n    at Immediate._onImmediate (/home/admin/apps/sbc-outbound/node_modules/drachtio-srf/lib/dialog.js:589:21)\n    at processImmediate (node:internal/timers:466:21)"
    },
    "msg": "Error handing INFO request on uac leg"
}
```

Regex [here ](https://github.com/jambonz/sbc-outbound/blob/f6c0ee6c0da1482ef9e5c3d1f059b6eca95ce2b4/lib/call-session.js#L761) should be:

```
/Signal=\s*([0-9#*])/
```

**Comment by davehorton** [comment]
Fixed.  Thanks!
